// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package controllers

import (
	models "carwashes/models"
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson7872ee0cDecodeCarwashesControllers(in *jlexer.Lexer, out *ServicesResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Services":
			if in.IsNull() {
				in.Skip()
				out.Services = nil
			} else {
				in.Delim('[')
				if out.Services == nil {
					if !in.IsDelim(']') {
						out.Services = make([]models.Service, 0, 1)
					} else {
						out.Services = []models.Service{}
					}
				} else {
					out.Services = (out.Services)[:0]
				}
				for !in.IsDelim(']') {
					var v1 models.Service
					(v1).UnmarshalEasyJSON(in)
					out.Services = append(out.Services, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7872ee0cEncodeCarwashesControllers(out *jwriter.Writer, in ServicesResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Services\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.Services == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Services {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ServicesResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7872ee0cEncodeCarwashesControllers(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ServicesResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7872ee0cEncodeCarwashesControllers(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ServicesResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7872ee0cDecodeCarwashesControllers(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ServicesResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7872ee0cDecodeCarwashesControllers(l, v)
}
