// +build ignore

// TEMPORARY AUTOGENERATED FILE: easyjson bootstapping code to launch
// the actual generator.

package main

import (
  "fmt"
  "os"

  "github.com/mailru/easyjson/gen"

  pkg "carwashes/models"
)

func main() {
  g := gen.NewGenerator("models_easyjson.go")
  g.SetPkg("models", "carwashes/models")
  g.Add(pkg.EasyJSON_exporter_Booking(nil))
  g.Add(pkg.EasyJSON_exporter_BookingService(nil))
  g.Add(pkg.EasyJSON_exporter_CarType(nil))
  g.Add(pkg.EasyJSON_exporter_CarWash(nil))
  g.Add(pkg.EasyJSON_exporter_CarWashes(nil))
  g.Add(pkg.EasyJSON_exporter_CarWashesWithOwnerName(nil))
  g.Add(pkg.EasyJSON_exporter_Client(nil))
  g.Add(pkg.EasyJSON_exporter_Histories(nil))
  g.Add(pkg.EasyJSON_exporter_MonthlyPaymentHistory(nil))
  g.Add(pkg.EasyJSON_exporter_Owner(nil))
  g.Add(pkg.EasyJSON_exporter_OwnerError(nil))
  g.Add(pkg.EasyJSON_exporter_OwnerWithWashes(nil))
  g.Add(pkg.EasyJSON_exporter_Service(nil))
  g.Add(pkg.EasyJSON_exporter_ServiceCost(nil))
  g.Add(pkg.EasyJSON_exporter_TopicPush(nil))
  g.Add(pkg.EasyJSON_exporter_TopicSubscribe(nil))
  g.Add(pkg.EasyJSON_exporter_WashOwners(nil))
  if err := g.Run(os.Stdout); err != nil {
    fmt.Fprintln(os.Stderr, err)
    os.Exit(1)
  }
}
